### ISSUE TITLE
User Story #13: Set Up Email Verification

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#14]
**Description:**

As a user, I want to verify my email address so that my account is more secure.

**Tasks:**

- [x] Configure Django Allauth for email verification.

- [x] Implement email sending functionality.

- [x] Create email templates.

**Acceptance Criteria:**

Email verification is functional.
Users receive a verification email upon registration.

**Comment by angelaanjorin** [comment]
Completed.
