### ISSUE TITLE
User Story #3: Create Frontend Interface for all products

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#22]
**Description:**

As a user, I want to easily find and view products that interest me through a frontend interface complete with a filtering system into categories.

**Tasks:**

- [x] Create frontend components for listing all products.

- [x] Implement a filtering system for the product lists.

- [x] Create frontend components for viewing the product details.

**Acceptance Criteria:**

Frontend components for listing and filtering products are functional.
Frontend components for viewing the product details are functional.

**Comment by angelaanjorin** [comment]
Completed
