### ISSUE TITLE
User Story #4: Implement Add to Cart Functionality

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#23]
**Description:**

As a user, I want to add products to a cart before finalizing my shopping, and I want to include specific contexts like selected sizes and colours.

**Tasks:**

- [x] Design and implement a cart model in the database with contexts.

- [x] Develop API endpoints for adding items to the cart, viewing the cart, and removing items from the cart.

- [x] Create frontend components for adding items to the cart, including context-based functionalities.

**Acceptance Criteria:**

I can add products to a cart with specific contexts (e.g., size, number of samples and colour, etc.).
Cart data with contexts is correctly stored and can be retrieved.
I can view my cart before proceeding to checkout.

**Comment by angelaanjorin** [comment]
Completed
