### ISSUE TITLE
User Story #6: Implement Stripe Webhooks

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#29]
**Description:**

As a developer, I want to set up and handle Stripe webhooks so that the backend can receive real-time notifications about payment events and update the application state accordingly.

**Tasks:**
- [x] Register webhooks in the Stripe Dashboard.

- [x] Create a webhook endpoint in the backend to handle Stripe events.

- [x] Implement logic to update application state based on received webhook events.

**Acceptance Criteria:**

Webhooks are registered in the Stripe Dashboard.
A backend endpoint to handle Stripe webhook events is functional.
The application state is correctly updated based on received webhook events (e.g., marking a product as paid upon payment success).

**Comment by angelaanjorin** [comment]
Completed after bugfix with the charges attribute no longer available directly from the payment intent. To get the billing_details the stripe_charge has to be gotten from stripe.
# Get the Charge object
        stripe_charge = stripe.Charge.retrieve(
            intent.latest_charge
        )

        billing_details = stripe_charge.billing_details # updated
        shipping_details = intent.shipping
        grand_total = round(stripe_charge.amount / 100, 2) # updated
