### ISSUE TITLE
User Story #2: Admin Functionalities for Products and User Management

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#31]
**Description:**

As an admin, I want to manage products and users from the admin panel so that I can perform essential admin tasks efficiently.
As an admin, I want to manage products from the website so that I can perform CRUD functionality also when logged into the site.

**Tasks:**
- [x] Implement product management features in the admin panel.

- [x] Implement user management features in the admin panel, including handling refund requests.

- [x] Implement product management features from the website.

**Acceptance Criteria:**

I can create, update, and delete products from the admin panel and from the website.
I can manage user accounts and handle refund requests from the admin panel.

**Comment by angelaanjorin** [comment]
Completed.
