### ISSUE TITLE
User Story #4: User Profile Page

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#33]
**Description:**

As a user, I want a profile page where I can view and edit my personal information, my wish list and reviews, see my past purchases and request refunds.

**Tasks:**
- [x] Design and implement a user profile page.
- [x] Enable viewing and editing of personal information.
- [x] Display past purchases .
- [ ] #64
- [ ] #65

**Acceptance Criteria:**
I can view and edit my personal information on the profile page.
I can see my past purchase history on the profile page.

**Comment by angelaanjorin** [comment]
Changed the last to tasks as they involve creating the review and wish functionality first.
All other tasks completed.
