### ISSUE TITLE
User Story #4: Email Notifications Setup

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#38]
**Description:**

As a user, I want to receive email notifications for essential activities like registration, password reset, and order confirmation, so I can stay informed.

**Tasks:**

- [x] Set up an email notification system for user registration.
- [x] Set up an email notification system for password reset.
- [x] Set up an email notification system for order confirmation.

**Acceptance Criteria:**

Emails are sent out for registration, password resets, and order confirmation with relevant information.

**Comment by angelaanjorin** [comment]
Completed
