### ISSUE TITLE
User Story #1: Reviews Functionality

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#40]
**Description:**

As a user, I want to read and write reviews for purchased products so that I can make more informed decisions later on and share my experiences.

**Tasks:**
- [x] Implement a review system for each product.
- [x] Display user-generated reviews in a readable format.
- [x] Apply CRUD functionality to the rewiews.

**Acceptance Criteria:**

Users can write reviews for the products.
Users can read reviews from other users.
Users can edit and delete thier reviews.

**Comment by angelaanjorin** [comment]
Completed.
