### ISSUE TITLE
User Story #3: Bug Fixing

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#53]
**Description:**
As a developer, I want to identify and fix all critical and non-critical bugs so that users have a smooth experience.

**Tasks:**
- [x] Identify existing bugs through testing.
- [x] Prioritize and fix the bugs.

**Acceptance Criteria:**

All identified bugs are listed.
Critical and high-priority bugs are fixed.

**Comment by angelaanjorin** [comment]
Due to lack of time I have some bugs still in my project.

- [ ]  The crispy issue due to my project first using Bootstrap5 and later having to implement a lot of code from the Boutique Ado project the forms due not render the labels of the form fields.
