### ISSUE TITLE
Bugfixes:

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#61]
Bugfixes:

- [x]  Fix the bug of the javascripts not rendering in the right order 

- [x] Correct the quantity input bug when the same product had different sizes in the bag

- [x] Adjust the add to bag view to show success toast messages for updating, removing and adding products to the bag in consideration of sizes when applicable.

**Comment by angelaanjorin** [comment]
Completed
