### ISSUE TITLE
User Story #8: Create AWS S3 Buckets

### ISSUE THREAD

**Issue by angelaanjorin** [angelaanjorin/Hair-Hotty#8]
**Description:**

As a developer, I want to create AWS S3 buckets so that we have a dedicated place to store static and media files.

**Tasks:**

- [x] Sign in to the AWS Management Console or create a new account.

- [x] Navigate to the S3 service and create new buckets for static and media files.

- [x] Configure bucket permissions and policies.

**Acceptance Criteria:**

AWS S3 buckets for static and media files are created.
Appropriate permissions and policies are set.

**Comment by angelaanjorin** [comment]
Completed after Bugfix of  due to using django 5 instead of 4 as in the Boutique_ado Walkthrough project. 
I had to replace   STATICFILES_STORAGE = 'custom_storages.StaticStorage' and  DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage' with  STORAGES = {"default": { "BACKEND": "custom_storages.MediaStorage", },
                              "staticfiles": {"BACKEND": "custom_storages.StaticStorage"},}
